---
# ConfigMap para MariaDB
apiVersion: v1
kind: ConfigMap
metadata:
  name: mariadb-config
  namespace: wordpress-phpmyadmin-db
data:
  my.cnf: |
    [mysqld]
    bind-address = 0.0.0.0
    port = 3306
    character-set-server = utf8mb4
    collation-server = utf8mb4_unicode_ci
    default-storage-engine = innodb
    innodb_buffer_pool_size = 256M
    max_connections = 200
    [mysql]
    default-character-set = utf8mb4
  mariadb.conf: |
    [server]
    default_storage_engine=innodb
    innodb_buffer_pool_size=256M
    innodb_log_file_size=64M
    innodb_flush_log_at_trx_commit=1
    innodb_flush_method=O_DIRECT
    [client]
    default-character-set=utf8mb4
  init.sql: |
    CREATE USER IF NOT EXISTS 'admin'@'%' IDENTIFIED BY 'password123';
    GRANT ALL PRIVILEGES ON *.* TO 'admin'@'%' WITH GRANT OPTION;
    FLUSH PRIVILEGES;

---
# ConfigMap para WordPress
apiVersion: v1
kind: ConfigMap
metadata:
  name: wordpress-config
  namespace: wordpress-phpmyadmin-db
data:
  WORDPRESS_DB_HOST: "mariadb-service"
  WORDPRESS_DB_PORT: "3306"
  WORDPRESS_DB_NAME: "wordpress"
  WORDPRESS_TABLE_PREFIX: "wp_"
  WORDPRESS_DEBUG: "1"
  WORDPRESS_ENABLE_HTTPS: "no"
  WORDPRESS_HTACCESS_OVERRIDE_NONE: "no"
  WORDPRESS_HTACCESS_OVERRIDE_DEFAULT: "no"

---
# Secret con todas las credenciales
apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secret
  namespace: wordpress-phpmyadmin-db
type: Opaque
data:
  root-password: YWRtaW4xMjM= #admin123
  
  database: d29yZHByZXNz #wordpress
  
  username: d29yZHByZXNz #wordpress
  
  password: d29yZHByZXNzMTIz #wordpress123
  
  phpmyadmin-database: dGVzdGRi #testbd
  
  phpmyadmin-username: YWRtaW4= #admin
  
  phpmyadmin-password: cGFzc3dvcmQxMjM= #password123